INSERT INTO curso VALUES (1, 'Ciencias da Computacao');
INSERT INTO curso VALUES (2, 'Geografia');
INSERT INTO curso VALUES (3, 'Engenharia Eletrica');
INSERT INTO curso VALUES (4, 'Engenharia Mecanica');
INSERT INTO curso VALUES (5, 'Sistemas da Informacao');
INSERT INTO curso VALUES (6, 'Jornalismo');
INSERT INTO curso VALUES (7, 'Design');
INSERT INTO curso VALUES (8, 'Biologia');
INSERT INTO curso VALUES (9, 'Física');

INSERT INTO pessoa VALUES (1, 'Joslindo', 'M', 'joslind@scc.e', 3);
INSERT INTO pessoa VALUES (2, 'Mary', 'F', 'mary@scc.e', 1);
INSERT INTO pessoa VALUES (3, 'Ana', 'F', 'ana@scc.e', 5);
INSERT INTO pessoa VALUES (4, 'Roberto', 'M', 'roberto@scc.e', 2);
INSERT INTO pessoa VALUES (5, 'Wilson', 'M', 'wilson@island.e', 4);
INSERT INTO pessoa VALUES (6, 'John', 'M', 'john@scc.e', 3);
INSERT INTO pessoa VALUES (7, 'Mariana', 'F', 'marin@scc.e', 2);
INSERT INTO pessoa VALUES (8, 'Carina', 'F', 'carin@scc.e', 4);
INSERT INTO pessoa VALUES (9, 'Fausto', 'M', 'fausto@cee.e', 1);
INSERT INTO pessoa VALUES (10, 'Bernardo', 'M', 'bernardo@cee.e',1);
INSERT INTO pessoa VALUES (11, 'Fernando', 'M', 'fernando@cee.e', 5);
INSERT INTO pessoa VALUES (12, 'Paulo', 'M', 'paulo@cee.e', 5);
INSERT INTO pessoa VALUES (13, 'Maria', 'F', 'maria@cee.e', 2);
INSERT INTO pessoa VALUES (14, 'Paula', 'F', 'paula@cee.e', 4);
INSERT INTO pessoa VALUES (15, 'Fernanda', 'F', 'fernanda@cee.e', 9);
INSERT INTO pessoa VALUES (16, 'Maria Alice', 'F', 'mariaAlice@scc.e', 7);
INSERT INTO pessoa VALUES (17, 'Alice', 'F', 'alice@scc.e', 7);
INSERT INTO pessoa VALUES (18, 'Alessandra', 'F', 'alessandra@scc.e', 6);
INSERT INTO pessoa VALUES (19, 'Alexandre', 'M', 'alexandre@see.c',8);
INSERT INTO pessoa VALUES (20, 'Jardilson', 'M', 'jardilson@scc.e', 9);
INSERT INTO pessoa VALUES (21, 'Logaritmo', 'M', 'log@scc.e', 6);
INSERT INTO pessoa VALUES (22, 'Sergio', 'M', 'sergio@see.e', 8);
INSERT INTO pessoa VALUES (23, 'Cleiton', 'M', 'cleiton@scc.e', 9);

INSERT INTO outroEmail VALUES (15, 'fer@see.c');
INSERT INTO outroEmail VALUES (10, 'ber4269@fss.e');
INSERT INTO outroEmail VALUES (20, 'dilso@sse.c');
INSERT INTO outroEmail VALUES (18, 'ale@gge.c');
INSERT INTO outroEmail VALUES (12, 'paulao@mme.m');
INSERT INTO outroEmail VALUES (22, 'charlvl22@gee.g');
INSERT INTO outroEmail VALUES (1, 'lindo@gee.g');
INSERT INTO outroEmail VALUES (4, 'betao@sce.g');
INSERT INTO outroEmail VALUES (6, 'johnatan@ces.g');
INSERT INTO outroEmail VALUES (8, 'cari897@cee.g');

INSERT INTO projeto (codProj, nomeProj, anoInicio, anoFim) VALUES (1, 'Desenvolvimento de plantas', 2011, 2015);
INSERT INTO projeto (codProj, nomeProj, anoInicio, anoFim) VALUES (2, 'Estudo de cidades', 2005, 2006);
INSERT INTO projeto (codProj, nomeProj, anoInicio, anoFim) VALUES (3, 'Propagandas e imagens', 2001, 2002);
INSERT INTO projeto VALUES (4, 'Plantas para dominação mundial', 2016, 2020, 1);
INSERT INTO projeto VALUES (5, 'SmartCities', 2008, 2016, 2);

INSERT INTO ProjetoPessoa VALUES (1, 4, 'Bolsista');
INSERT INTO ProjetoPessoa VALUES (1, 7, 'Membro');
INSERT INTO ProjetoPessoa VALUES (1, 19, 'Líder');
INSERT INTO ProjetoPessoa VALUES (1, 22, 'Membro');
INSERT INTO ProjetoPessoa VALUES (1, 20, 'Membro');
INSERT INTO ProjetoPessoa VALUES (2, 7, 'Líder');
INSERT INTO ProjetoPessoa VALUES (2, 1, 'Membro');
INSERT INTO ProjetoPessoa VALUES (2, 5, 'Membro');
INSERT INTO ProjetoPessoa VALUES (2, 9, 'Membro');
INSERT INTO ProjetoPessoa VALUES (2, 8, 'Membro');
INSERT INTO ProjetoPessoa VALUES (3, 16, 'Líder');
INSERT INTO ProjetoPessoa VALUES (3, 17, 'Membro');
INSERT INTO ProjetoPessoa VALUES (3, 2, 'Membro');
INSERT INTO ProjetoPessoa VALUES (3, 10, 'Bolsista');
INSERT INTO ProjetoPessoa VALUES (3, 11, 'Bolsista');
INSERT INTO ProjetoPessoa VALUES (3, 18, 'Líder');
INSERT INTO ProjetoPessoa VALUES (3, 21, 'Membro');
INSERT INTO ProjetoPessoa VALUES (4, 19, 'Líder');
INSERT INTO ProjetoPessoa VALUES (4, 22, 'Líder');
INSERT INTO ProjetoPessoa VALUES (4, 23, 'Membro');
INSERT INTO ProjetoPessoa VALUES (4, 20, 'Membro');
INSERT INTO ProjetoPessoa VALUES (4, 15, 'Membro');
INSERT INTO ProjetoPessoa VALUES (4, 4, 'Bolsista');
INSERT INTO ProjetoPessoa VALUES (5, 2, 'Líder');
INSERT INTO ProjetoPessoa VALUES (5, 9, 'Membro');
INSERT INTO ProjetoPessoa VALUES (5, 10, 'Bolsista');
INSERT INTO ProjetoPessoa VALUES (5, 6, 'Bolsista');
INSERT INTO ProjetoPessoa VALUES (5, 8, 'Membro');
INSERT INTO ProjetoPessoa VALUES (5, 5, 'Membro');
INSERT INTO ProjetoPessoa VALUES (5, 7, 'Membro');